site_name: NethServer Cockpit
theme:
    name: material
    palette:
        primary: blue grey
        accent: indigo
    logo:
        icon: 'build'
site_url: https://nethserver.github.io/nethserver-cockpit
repo_url: https://github.com/NethServer/nethserver-cockpit
edit_uri: edit/master/docs/docs/
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
nav:
- Home: index.md
- API:
    - General:
      - api_guidelines.md
      - api_protocol.md
      - api_libraries.md
    - Helpers:
      - api/system-aliases.md
      - api/system-apps.md
      - api/system-certificate.md
      - api/system-company.md
      - api/system-dns.md
      - api/system-hostname.md
      - api/system-hosts.md
      - api/system-openssh.md
      - api/system-services.md
      - api/system-shutdown.md
      - api/system-status.md
      - api/system-task.md
      - api/system-time.md
      - api/system-tls-policy.md
      - api/system-trusted-networks.md
- User interface:
    - environment.md
    - ui_guidelines.md
    - application_manifest.md
- Tutorial:
    - new_module.md
- Build:
    - build_doc.md
    - build_rpm.md
- Manuals:
    - 'NethServer Developer manual': 'http://docs.nethserver.org/projects/nethserver-devel'
    - 'NethServer Administrator manual': 'http://docs.nethserver.org'
    - 'Cockpit Guide': 'http://cockpit-project.org/guide/latest/'
