site_name: NethServer Cockpit
theme:
    name: material
    palette:
        primary: blue grey
        accent: indigo
    logo:
        icon: 'build'
site_url: https://nethserver.github.io/nethserver-cockpit
repo_url: https://github.com/NethServer/nethserver-cockpit
edit_uri: edit/master/docs/docs/
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
nav:
- Home: index.md
- API:
    - General:
      - api_guidelines.md
      - api_protocol.md
      - api_libraries.md
    - System helpers:
      - api/system-accounts-provider.md
      - api/system-aliases.md
      - api/system-apps.md
      - api/system-authorization.md
      - api/system-backup.md
      - api/system-certificate.md
      - api/system-company.md
      - api/system-dhcp.md
      - api/system-disk-usage.md
      - api/system-docs.md
      - api/system-dns.md
      - api/system-hostname.md
      - api/system-hosts.md
      - api/system-logs.md
      - api/system-network.md
      - api/system-openssh.md
      - api/system-password.md
      - api/system-password-policy.md
      - api/system-packages.md
      - api/system-proxy.md
      - api/system-roles.md
      - api/system-routes.md
      - api/system-services.md
      - api/system-settings.md
      - api/system-shutdown.md
      - api/system-status.md
      - api/system-subscription.md
      - api/system-task.md
      - api/system-time.md
      - api/system-tls-policy.md
      - api/system-trusted-networks.md
      - api/system-users.md
    - Firewall helpers:
      - api/nethserver-firewall-base/connections.md
      - api/nethserver-firewall-base/dashboard.md
      - api/nethserver-firewall-base/local-rules.md
      - api/nethserver-firewall-base/objects.md
      - api/nethserver-firewall-base/port-forward.md
      - api/nethserver-firewall-base/rules.md
      - api/nethserver-firewall-base/settings.md
      - api/nethserver-firewall-base/snat.md
      - api/nethserver-firewall-base/traffic-shaping.md
      - api/nethserver-firewall-base/wan.md
    - Mail helpers:
      - api/nethserver-mail/connectors.md
      - api/nethserver-mail/dashboard.md
      - api/nethserver-mail/domains.md
      - api/nethserver-mail/filter.md
      - api/nethserver-mail/mailbox.md
      - api/nethserver-mail/feature.md
      - api/nethserver-mail/pseudonym.md
      - api/nethserver-mail/queue.md
      - api/nethserver-mail/send.md
      - api/nethserver-mail/settings.md
    - Samba helpers:
      - api/nethserver-samba/audit.md
      - api/nethserver-samba/dashboard.md
      - api/nethserver-samba/sharedfolders.md
      - api/nethserver-samba/settings.md
    - Web proxy helpers:
      - api/nethserver-squid/categories.md
      - api/nethserver-squid/dashboard.md
      - api/nethserver-squid/feature.md
      - api/nethserver-squid/filter.md
      - api/nethserver-squid/proxy.md
      - api/nethserver-squid/rules.md
    - IPS helpers:
      - api/nethserver-suricata/configuration.md
      - api/nethserver-suricata/dashboard.md
    - UPS helpers:
      - api/nethserver-nut/dashboard.md
      - api/nethserver-nut/settings.md
    - VPN helpers:
      - api/nethserver-vpn/dashboard.md
      - api/nethserver-vpn/feature.md
      - api/nethserver-vpn/ipsec.md
      - api/nethserver-vpn/logs.md
      - api/nethserver-vpn/openvpn-rw.md
      - api/nethserver-vpn/openvpn-tunnel.md
    - HTTP helpers:
      - api/nethserver-httpd/dashboard.md
      - api/nethserver-httpd/feature.md
      - api/nethserver-httpd/ftp.md
      - api/nethserver-httpd/proxypass.md
      - api/nethserver-httpd/virtualhost.md
- UI:
  - ui_guidelines.md
  - i18n.md
- authorizations.md
- environment.md
- application_manifest.md
- tutorial.md
- Build:
    - build_doc.md
    - build_rpm.md
- Manuals:
    - 'NethServer Developer manual': 'http://docs.nethserver.org/projects/nethserver-devel'
    - 'NethServer Administrator manual': 'http://docs.nethserver.org'
    - 'Cockpit Guide': 'http://cockpit-project.org/guide/latest/'
